sudo: required

language: python

services:
  - docker

script:
  - docker build -t borisbabiy/nagios-yaml .

after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
      docker push borisbabiy/nagios-yaml
    fi
