sudo: required

language: python

services:
  - docker

script:
  - docker build -t borisbabiy/nagios-yaml:latest -t borisbabiy/nagios-yaml:$(cat version.txt) .

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
